### ISSUE TITLE
cannot login to Phoenix

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-reva#63]
since 11816f75ab002bdc0d736d20d97e997c1348d732 its impossible to login to Phoenix

to reproduce:
1. from ocis repo start micro and phoenix `bin/ocis micro & bin/ocis phoenix`
2. start reva with 
```
bin/ocis-reva gateway & bin/ocis-reva users & bin/ocis-reva auth-basic & bin/ocis-reva auth-bearer & bin/ocis-reva sharing & bin/ocis-reva storage-root & REVA_STORAGE_HOME_EXPOSE_DATA_SERVER=1 bin/ocis-reva storage-home & bin/ocis-reva storage-home-data & REVA_STORAGE_OC_EXPOSE_DATA_SERVER=1 bin/ocis-reva storage-oc & bin/ocis-reva storage-oc-data & bin/ocis-reva frontend
```

while starting an error is shown:
```
10:38AM INF home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/cmd/revad/runtime/runtime.go:65 > host info: artur-OptiPlex-3050 pid=10443
panic: interface conversion: flag.Value is *flag.stringValue, not *cli.StringSlice

goroutine 1 [running]:
github.com/micro/cli/v2.lookupStringSlice(...)
	10:38AM INF home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/cmd/revad/runtime/runtime.go:141 > running on 4 cpus pid=10443
/home/artur/go/pkg/mod/github.com/micro/cli/v2@v2.1.1/flag_string_slice.go:152
github.com/micro/cli/v2.(*Context).StringSlice(0xc00049f180, 0x11cb9ad, 0x7, 0xc0005eb440, 0x4, 0x0)
	/home/artur/go/pkg/mod/github.com/micro/cli/v2@v2.1.1/flag_string_slice.go:144 +0x104
github.com/owncloud/ocis-reva/pkg/command.Users.func1(0xc00049f180, 0x1d, 0x38)
	/home/artur/www/ocis-reva/pkg/command/users.go:26 +0x4d
github.com/micro/cli/v2.(*Command).Run(0xc0005e212010:38AM INF home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/cmd/revad/internal/grace/grace.go:181 > pidfile saved at: /tmp/revad-storage-home-data-24ec9eeb-0ad6-4944-b9d2-d6bfed533214.pid pid=10443 pkg=grace
, 0xc00049e940, 0x0, 0x0)
	/home/artur/go/pkg/mod/github.com/micro/cli/v2@v2.1.1/command.go:148 +0x57c
github.com/micro/cli/v2.(*App).RunContext(0xc0005f2000, 0x17db4c0, 0xc0000b8010, 0xc0000be000, 0x2, 0x2, 0x0, 0x0)
	/home/artur/go/pkg/mod/github.com/micro/cli/v2@v2.1.1/app.go:302 +0x790
github.com/micro/cli/v2.(*App).Run(...)
	/home/artur/go/pkg/mod/github.com/micro/cli/v2@v2.1.1/app.go:210
github.com/owncloud/ocis-reva/pkg/command.Execute(0x9e000, 0xc00009c058)
10:38AM INF home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/pkg/rhttp/rhttp.go:206 > http service enabled: dataprovider@/data pid=10443 pkg=rhttp
	/home/artur/www/ocis-reva/pkg/command/root.go:102 +0xa12
main.main()
	/home/artur/www/ocis-reva/cmd/ocis-reva/main.go:10 +0x22
10:38AM INF home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/pkg/rhttp/rhttp.go:107 > http server listening at http://0.0.0.0:9156 pid=10443 pkg=rhttp
{"level":"info","service":"reva","time":"2020-01-30T10:38:37+05:45","message":"Continue without config"}
{"level":"info","service":"reva","transport":"debug","addr":"0.0.0.0:9141","time":"2020-01-30T10:38:37+05:45","message":"Starting server"}
10:38AM INF home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/cmd/revad/runtime/runtime.go:65 > host info: artur-OptiPlex-3050 pid=10450
```

when trying to login to phoenix Login Error Page is shown in Phoenix and this error in the reva log output:

```
10:39AM INF home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/services/oidcprovider/oidcprovider.go:169 > oidcprovider routing: head=userinfo tail=/ pid=10450 pkg=rhttp traceid=8ab17023c2f50b7176c14c2fd71e5cb1
internal token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNTgwMzYzNjU5LCJpYXQiOjE1ODAzNjAwNTksImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTk5OCIsInVzZXIiOnsiaWQiOnsiaWRwIjoiaHR0cDovL2xvY2FsaG9zdDo5OTk4Iiwib3BhcXVlX2lkIjoiNGM1MTBhZGEtYzg2Yi00ODE1LTg4MjAtNDJjZGY4MmMzZDUxIn0sInVzZXJuYW1lIjoiZWluc3RlaW4iLCJtYWlsIjoiZWluc3RlaW5AZXhhbXBsZS5vcmciLCJkaXNwbGF5X25hbWUiOiJBbGJlcnQgRWluc3RlaW4iLCJncm91cHMiOlsic2FpbGluZy1sb3ZlcnMiLCJ2aW9saW4taGF0ZXJzIiwicGh5c2ljcy1sb3ZlcnMiXX19.JcfMNgHxDndOGuAGI5hKCesTC68pQt6lSJkzwhcHZEE subject: 4c510ada-c86b-4815-8820-42cdf82c3d51 session:&{DefaultSession:0xc000553280 internalToken:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNTgwMzYzNjU5LCJpYXQiOjE1ODAzNjAwNTksImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTk5OCIsInVzZXIiOnsiaWQiOnsiaWRwIjoiaHR0cDovL2xvY2FsaG9zdDo5OTk4Iiwib3BhcXVlX2lkIjoiNGM1MTBhZGEtYzg2Yi00ODE1LTg4MjAtNDJjZGY4MmMzZDUxIn0sInVzZXJuYW1lIjoiZWluc3RlaW4iLCJtYWlsIjoiZWluc3RlaW5AZXhhbXBsZS5vcmciLCJkaXNwbGF5X25hbWUiOiJBbGJlcnQgRWluc3RlaW4iLCJncm91cHMiOlsic2FpbGluZy1sb3ZlcnMiLCJ2aW9saW4taGF0ZXJzIiwicGh5c2ljcy1sb3ZlcnMiXX19.JcfMNgHxDndOGuAGI5hKCesTC68pQt6lSJkzwhcHZEE}10:39AM ERR home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/grpc/interceptors/log/log.go:69 > unary code=Unknown end="30/Jan/2020:10:39:20 +0545" from=tcp://127.0.0.1:52456 pid=10436 pkg=rgrpc start="30/Jan/2020:10:39:20 +0545" time_ns=271492 traceid=8ab17023c2f50b7176c14c2fd71e5cb1 uri=/cs3.gateway.v1beta1.GatewayAPI/GetUser user-agent=grpc-go/1.26.0
10:39AM ERR home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/services/oidcprovider/userinfo.go:99 > error calling GetUser error="rpc error: code = Unknown desc = gateway: error calling GetUser: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:9144: connect: connection refused\"" pid=10450 pkg=rhttp traceid=8ab17023c2f50b7176c14c2fd71e5cb1
10:39AM ERR home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/interceptors/log/log.go:112 > http end="30/Jan/2020:10:39:20 +0545" host=127.0.0.1 method=GET pid=10450 pkg=rhttp proto=HTTP/1.1 size=0 start="30/Jan/2020:10:39:20 +0545" status=500 time_ns=1097640 traceid=8ab17023c2f50b7176c14c2fd71e5cb1 uri=/oauth2/userinfo url=/oauth2/userinfo
```

**Comment by butonic** [comment]
fixed with https://github.com/owncloud/ocis-reva/pull/76
related https://github.com/owncloud/ocis-reva/issues/75
