### ISSUE TITLE
sharing fails with `error searching recipient`

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-reva#64]
since 11816f7 its impossible to share

to reproduce:
1. from ocis repo start micro and phoenix0 `bin/ocis micro & bin/ocis phoenix`
2. start reva with
```
bin/ocis-reva gateway & bin/ocis-reva users & bin/ocis-reva auth-basic & bin/ocis-reva auth-bearer & bin/ocis-reva sharing & bin/ocis-reva storage-root & REVA_STORAGE_HOME_EXPOSE_DATA_SERVER=1 bin/ocis-reva storage-home & bin/ocis-reva storage-home-data & REVA_STORAGE_OC_EXPOSE_DATA_SERVER=1 bin/ocis-reva storage-oc & bin/ocis-reva storage-oc-data & bin/ocis-reva frontend
```
3. upload a file `curl -X PUT http://localhost:9140/remote.php/webdav/home/textfile0.txt -d "123" -u einstein:relativity`
4. make sure the file is uploaded `curl -X PROPFIND http://localhost:9140/remote.php/webdav/home -u einstein:relativity`
5. try to share the file `curl -X POST http://localhost:9140/ocs/v1.php/apps/files_sharing/api/v1/shares -u einstein:relativity -d "permissions=31&path=%2Fhome%2Ftextfile0.txt&shareType=0&shareWith=richard"`

result: `<ocs><meta><status>error</status><statuscode>996</statuscode><message>error searching recipient</message></meta></ocs>`

reva console output
```
10:48AM ERR home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/grpc/interceptors/log/log.go:69 > unary code=Unknown end="30/Jan/2020:10:48:49 +0545" from=tcp://127.0.0.1:54230 pid=11904 pkg=rgrpc start="30/Jan/2020:10:48:49 +0545" time_ns=644448 traceid=2a8408e117c0d1ef98524e3db15b7001 uri=/cs3.gateway.v1beta1.GatewayAPI/FindUsers user-agent=grpc-go/1.26.0
10:48AM ERR home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/services/owncloud/ocs/reqres.go:94 > error searching recipient error="rpc error: code = Unknown desc = gateway: error calling GetUser: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:9144: connect: connection refused\"" pid=11922 pkg=rhttp traceid=2a8408e117c0d1ef98524e3db15b7001
```

**Comment by individual-it** [comment]
The behaviour changed

## Steps to reproduce the current issue in CI manually:
all steps done using LDAP. Reva started with this command: 
```
bin/ocis-reva gateway &\
bin/ocis-reva users & \
REVA_USERS_DRIVER=ldap bin/ocis-reva auth-basic & \
bin/ocis-reva auth-bearer &  \
bin/ocis-reva sharing &  \
bin/ocis-reva storage-root &  \
REVA_STORAGE_HOME_EXPOSE_DATA_SERVER=1 bin/ocis-reva storage-home &  \
bin/ocis-reva storage-home-data &  \
REVA_STORAGE_OC_EXPOSE_DATA_SERVER=1 bin/ocis-reva storage-oc &  \
bin/ocis-reva storage-oc-data &  \
bin/ocis-reva frontend
```

1. Upload a file: `curl -u user0:123456 -X PUT http://localhost:9140/remote.php/webdav/textfile0.txt -d "data for file"`
2. make sure the file is there and PROPFIND works on both endpoints `curl -u user0:123456 -X PROPFIND http://localhost:9140/remote.php/webdav/textfile0.txt`
`curl -u user0:123456 -X PROPFIND http://localhost:9140/remote.php/dav/files/user0/textfile0.txt`
3. try to share the file with different path:
  - `%2Fhome%2Ftextfile0.txt`:  `curl -u user0:123456 -X POST http://localhost:9140/ocs/v1.php/apps/files_sharing/api/v1/shares -d "permissions=31&path=%2Fhome%2Ftextfile0.txt&shareType=0&shareWith=user1" -v`
  - `%2Ftextfile0.txt`:  `curl -u user0:123456 -X POST http://localhost:9140/ocs/v1.php/apps/files_sharing/api/v1/shares -d "permissions=31&path=%2Ftextfile0.txt&shareType=0&shareWith=user1" -v`
  - `textfile0.txt`:  `curl -u user0:123456 -X POST http://localhost:9140/ocs/v1.php/apps/files_sharing/api/v1/shares -d "permissions=31&path=textfile0.txt&shareType=0&shareWith=user1" -v`

## Results
### with with 2b2e7f05c54ba7aafcb372d0cf1858fbbc2e8d0a
in every case the result is:
```
HTTP/1.1 200 OK

<?xml version="1.0" encoding="UTF-8"?>
<ocs><meta><status>error</status><statuscode>996</statuscode><message>error searching recipient</message></meta></ocs>
```

### with ac3381e
- `%2Fhome%2Ftextfile0.txt`: Empty reply from server
   ocis-log:

```
2020/02/12 09:22:53 http: panic serving 127.0.0.1:34246: runtime error: invalid memory address or nil pointer dereference
goroutine 15 [running]:
net/http.(*conn).serve.func1(0xc00055a000)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x1048a80, 0x1ff0180)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cs3org/reva/internal/http/services/owncloud/ocs.(*SharesHandler).createShare(0xc000444d50, 0x7f6776913fd8, 0xc000513f20, 0xc000292600)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/services/owncloud/ocs/shares.go:262 +0x80e
github.com/cs3org/reva/internal/http/services/owncloud/ocs.(*SharesHandler).ServeHTTP(0xc000444d50, 0x7f6776913fd8, 0xc000513f20, 0xc000292600)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/services/owncloud/ocs/shares.go:73 +0x351
github.com/cs3org/reva/internal/http/services/owncloud/ocs.(*AppsHandler).ServeHTTP(0xc000444d40, 0x7f6776913fd8, 0xc000513f20, 0xc000292600)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/services/owncloud/ocs/apps.go:49 +0x3e2
github.com/cs3org/reva/internal/http/services/owncloud/ocs.(*V1Handler).Handler.func1(0x7f6776913fd8, 0xc000513f20, 0xc000292600)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/services/owncloud/ocs/v1.go:53 +0x1c8
net/http.HandlerFunc.ServeHTTP(0xc0005946a0, 0x7f6776913fd8, 0xc000513f20, 0xc000292600)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/services/owncloud/ocs.(*svc).Handler.func1(0x7f6776913fd8, 0xc000513f20, 0xc000292600)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/services/owncloud/ocs/ocs.go:95 +0x1ff
net/http.HandlerFunc.ServeHTTP(0xc000444d80, 0x7f6776913fd8, 0xc000513f20, 0xc000292600)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7f6776913fd8, 0xc000513f20, 0xc000292400)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/pkg/rhttp/rhttp.go:300 +0x185
net/http.HandlerFunc.ServeHTTP(0xc000486b10, 0x7f6776913fd8, 0xc000513f20, 0xc000292400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.(*Server).getHandler.func1(0x7f6776913fd8, 0xc000513f20, 0xc000292400)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/pkg/rhttp/rhttp.go:239 +0x287
net/http.HandlerFunc.ServeHTTP(0xc0001a6fb0, 0x7f6776913fd8, 0xc000513f20, 0xc000292400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7f6776913fd8, 0xc000513f20, 0xc000292300)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/pkg/rhttp/rhttp.go:300 +0x185
net/http.HandlerFunc.ServeHTTP(0xc000513320, 0x7f6776913fd8, 0xc000513f20, 0xc000292300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rs/cors.(*Cors).Handler.func1(0x7f6776913fd8, 0xc000513f20, 0xc000292300)
	/home/artur/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1b8
net/http.HandlerFunc.ServeHTTP(0xc0003d5780, 0x7f6776913fd8, 0xc000513f20, 0xc000292300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7f6776913fd8, 0xc000513f20, 0xc000292200)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/pkg/rhttp/rhttp.go:300 +0x185
net/http.HandlerFunc.ServeHTTP(0xc0005136e0, 0x7f6776913fd8, 0xc000513f20, 0xc000292200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/auth.New.func1.1(0x7f6776913fd8, 0xc000513f20, 0xc00054cd00)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/interceptors/auth/auth.go:230 +0xdb9
net/http.HandlerFunc.ServeHTTP(0xc000414510, 0x7f6776913fd8, 0xc000513f20, 0xc00054cd00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7f6776913fd8, 0xc000513f20, 0xc00054cc00)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/pkg/rhttp/rhttp.go:300 +0x185
net/http.HandlerFunc.ServeHTTP(0xc000513710, 0x7f6776913fd8, 0xc000513f20, 0xc00054cc00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/log.loggingHandler.ServeHTTP(0x17c5620, 0xc000513710, 0x17dd080, 0xc0000a4a00, 0xc00054cc00)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/interceptors/log/log.go:57 +0x297
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x17dd080, 0xc0000a4a00, 0xc00054cb00)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/pkg/rhttp/rhttp.go:300 +0x185
net/http.HandlerFunc.ServeHTTP(0xc000513740, 0x17dd080, 0xc0000a4a00, 0xc00054cb00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/appctx.handler.func1(0x17dd080, 0xc0000a4a00, 0xc00054ca00)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v0.0.2-0.20200115110931-4c7513415ec5/internal/http/interceptors/appctx/appctx.go:52 +0x5e5
net/http.HandlerFunc.ServeHTTP(0xc000558070, 0x17dd080, 0xc0000a4a00, 0xc00054ca00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP(0xc0000a4550, 0x17dd080, 0xc0000a4a00, 0xc00054c800)
	/home/artur/go/pkg/mod/go.opencensus.io@v0.22.2/plugin/ochttp/server.go:92 +0x2b9
net/http.serverHandler.ServeHTTP(0xc0004da000, 0x17dc040, 0xc0004da0e0, 0xc00054c800)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00055a000, 0x17e1580, 0xc000081080)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
```
- `%2Ftextfile0.txt`: 
```
HTTP/1.1 200 OK
<?xml version="1.0" encoding="UTF-8"?>
<ocs><meta><status>error</status><statuscode>998</statuscode><message>not found</message></meta></ocs>
```
- `textfile0.txt`: 
```
HTTP/1.1 200 OK
<?xml version="1.0" encoding="UTF-8"?>
<ocs><meta><status>error</status><statuscode>996</statuscode><message>grpc stat request failed</message></meta></ocs>
```

**Comment by butonic** [comment]
some response codes got better with https://github.com/owncloud/ocis-reva/pull/113

see https://github.com/owncloud/core/pull/37149

**Comment by C0rby** [comment]
I think this ticket is outdated.
Can we close it?

**Comment by individual-it** [comment]
I suggest to enable tests that are tagged with this issue and retest, if PROPFIND only work on one endpoint tests should be split and also the issue
QA-team can take care of that next week

**Comment by kiranparajuli589** [comment]
The behaviour changed again

## Steps to reproduce:
1. upload a file:
```
curl -u user0:123456 -X PUT http://localhost:9140/remote.php/webdav/textfile0.txt -d "data for file" -v
```
2. make sure the file is there and PROPFIND works on both endpoints
```
curl -u user0:123456 -X PROPFIND http://localhost:9140/remote.php/webdav/textfile0.txt -v
curl -u user0:123456 -X PROPFIND http://localhost:9140/remote.php/dav/files/user0/textfile0.txt -v
```
3. try to share the file with different path:
  - `%2Fhome%2Ftextfile0.txt`:
  ```
  curl -u user0:123456 -X POST http://localhost:9140/ocs/v1.php/apps/files_sharing/api/v1/shares -d "permissions=31&path=%2Fhome%2Ftextfile0.txt&shareType=0&shareWith=user1" -v
  ```
  - `%2Ftextfile0.txt`:
  ```
  curl -u user0:123456 -X POST http://localhost:9140/ocs/v1.php/apps/files_sharing/api/v1/shares -d "permissions=31&path=%2Ftextfile0.txt&shareType=0&shareWith=user1" -v
  ```
  - `textfile0.txt`:
  ```
  curl -u user0:123456 -X POST http://localhost:9140/ocs/v1.php/apps/files_sharing/api/v1/shares -d "permissions=31&path=textfile0.txt&shareType=0&shareWith=user2" -v
  ```

## Results
- `%2Fhome%2Ftextfile0.txt`:
```xml
HTTP/1.1 200 OK

<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>error</status>
    <statuscode>998</statuscode>
    <message>not found</message>
  </meta>
</ocs>
```
  ocis log:
  ```
  2020-06-05T16:35:33+05:45 WRN core access token not set pkg=rhttp service=reva traceid=1b58f02361f8e106a7b187350885b088
  2020-06-05T16:35:33+05:45 INF unary code=OK end="05/Jun/2020:16:35:33 +0545" from=tcp://127.0.0.1:40114 pkg=rgrpc service=reva start="05/Jun/2020:16:35:33 +0545" time_ns=37353 traceid=1b58f02361f8e106a7b187350885b088 uri=/cs3.auth.registry.v1beta1.RegistryAPI/GetAuthProvider user-agent=grpc-go/1.29.1
  2020-06-05T16:35:33+05:45 INF user id:<idp:"https://localhost:9200" opaque_id:"user0" > username:"user0" mail:"user0@example.org" display_name:"One"  authenticated pkg=rgrpc service=reva traceid=1b58f02361f8e106a7b187350885b088
  2020-06-05T16:35:33+05:45 INF unary code=OK end="05/Jun/2020:16:35:33 +0545" from=tcp://127.0.0.1:46712 pkg=rgrpc service=reva start="05/Jun/2020:16:35:33 +0545" time_ns=21331651 traceid=1b58f02361f8e106a7b187350885b088 uri=/cs3.auth.provider.v1beta1.ProviderAPI/Authenticate user-agent=grpc-go/1.29.1
  2020-06-05T16:35:33+05:45 INF unary code=OK end="05/Jun/2020:16:35:33 +0545" from=tcp://127.0.0.1:40122 pkg=rgrpc service=reva start="05/Jun/2020:16:35:33 +0545" time_ns=153152 traceid=1b58f02361f8e106a7b187350885b088 uri=/cs3.storage.registry.v1beta1.RegistryAPI/GetStorageProvider user-agent=grpc-go/1.29.1
  2020-06-05T16:35:33+05:45 INF unary code=OK end="05/Jun/2020:16:35:33 +0545" from=tcp://127.0.0.1:58608 pkg=rgrpc service=reva start="05/Jun/2020:16:35:33 +0545" time_ns=335023 traceid=1b58f02361f8e106a7b187350885b088 uri=/cs3.storage.provider.v1beta1.ProviderAPI/CreateHome user-agent=grpc-go/1.29.1
  2020-06-05T16:35:33+05:45 INF unary code=OK end="05/Jun/2020:16:35:33 +0545" from=tcp://127.0.0.1:40112 pkg=rgrpc service=reva start="05/Jun/2020:16:35:33 +0545" time_ns=24824577 traceid=1b58f02361f8e106a7b187350885b088 uri=/cs3.gateway.v1beta1.GatewayAPI/Authenticate user-agent=grpc-go/1.29.1
  2020-06-05T16:35:33+05:45 INF core access token generated pkg=rhttp service=reva traceid=1b58f02361f8e106a7b187350885b088
  2020-06-05T16:35:33+05:45 INF unary code=OK end="05/Jun/2020:16:35:33 +0545" from=tcp://127.0.0.1:40112 pkg=rgrpc service=reva start="05/Jun/2020:16:35:33 +0545" time_ns=7309 traceid=1b58f02361f8e106a7b187350885b088 uri=/cs3.gateway.v1beta1.GatewayAPI/GetHome user-agent=grpc-go/1.29.1
  2020-06-05T16:35:33+05:45 INF unary code=OK end="05/Jun/2020:16:35:33 +0545" from=tcp://127.0.0.1:47756 pkg=rgrpc service=reva start="05/Jun/2020:16:35:33 +0545" time_ns=28177880 traceid=1b58f02361f8e106a7b187350885b088 uri=/cs3.identity.user.v1beta1.UserAPI/GetUser user-agent=grpc-go/1.29.1
  2020-06-05T16:35:33+05:45 INF unary code=OK end="05/Jun/2020:16:35:33 +0545" from=tcp://127.0.0.1:40112 pkg=rgrpc service=reva start="05/Jun/2020:16:35:33 +0545" time_ns=29623331 traceid=1b58f02361f8e106a7b187350885b088 uri=/cs3.gateway.v1beta1.GatewayAPI/GetUser user-agent=grpc-go/1.29.1
  2020-06-05T16:35:33+05:45 INF unary code=OK end="05/Jun/2020:16:35:33 +0545" from=tcp://127.0.0.1:40122 pkg=rgrpc service=reva start="05/Jun/2020:16:35:33 +0545" time_ns=102005 traceid=1b58f02361f8e106a7b187350885b088 uri=/cs3.storage.registry.v1beta1.RegistryAPI/GetStorageProvider user-agent=grpc-go/1.29.1
  2020-06-05T16:35:33+05:45 WRN home/kiran/go/pkg/mod/github.com/cs3org/reva@v0.1.1-0.20200603124923-9b9f2e5af0e9/internal/grpc/services/storageprovider/storageprovider.go:457 > file not found pkg=rgrpc service=reva traceid=1b58f02361f8e106a7b187350885b088
  2020-06-05T16:35:33+05:45 INF unary code=OK end="05/Jun/2020:16:35:33 +0545" from=tcp://127.0.0.1:58608 pkg=rgrpc service=reva start="05/Jun/2020:16:35:33 +0545" time_ns=477158 traceid=1b58f02361f8e106a7b187350885b088 uri=/cs3.storage.provider.v1beta1.ProviderAPI/Stat user-agent=grpc-go/1.29.1
  2020-06-05T16:35:33+05:45 INF unary code=OK end="05/Jun/2020:16:35:33 +0545" from=tcp://127.0.0.1:40112 pkg=rgrpc service=reva start="05/Jun/2020:16:35:33 +0545" time_ns=1348718 traceid=1b58f02361f8e106a7b187350885b088 uri=/cs3.gateway.v1beta1.GatewayAPI/Stat user-agent=grpc-go/1.29.1
  2020-06-05T16:35:33+05:45 INF http end="05/Jun/2020:16:35:33 +0545" host=127.0.0.1 method=POST pkg=rhttp proto=HTTP/1.1 service=reva size=141 start="05/Jun/2020:16:35:33 +0545" status=200 time_ns=58293689 traceid=1b58f02361f8e106a7b187350885b088 uri=/ocs/v1.php/apps/files_sharing/api/v1/shares url=/ocs/v1.php/apps/files_sharing/api/v1/shares
  ```
- `%2Ftextfile0.txt`: 
```xml
HTTP/1.1 200 OK

<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
  <data>
    <id>c99b869f-0830-424e-85b3-bd115ced6682</id><share_type>0</share_type><uid_owner>user0</uid_owner><displayname_owner>One</displayname_owner><permissions>19</permissions><stime>1591354468</stime><parent></parent><expiration></expiration><token></token><uid_file_owner>user0</uid_file_owner><displayname_file_owner>One</displayname_file_owner><additional_info_owner></additional_info_owner><additional_info_file_owner></additional_info_file_owner><state>0</state><path>/textfile0.txt</path><item_type>file</item_type><mimetype>text/plain</mimetype><storage_id>1284d238-aa92-42ce-bdc4-0b0000009162</storage_id><storage>0</storage><item_source>46e810dc-309a-49f0-ba68-d182fa12b1c5</item_source><file_source>46e810dc-309a-49f0-ba68-d182fa12b1c5</file_source><file_parent></file_parent><file_target>/textfile0.txt</file_target><share_with>user1</share_with><share_with_displayname>One</share_with_displayname><share_with_additional_info></share_with_additional_info><mail_send></mail_send><name></name>
  </data>
</ocs>            
```
- `textfile0.txt`: 
```xml
HTTP/1.1 200 OK

<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
  <data>
    <id>be914aab-9c8c-4285-80b9-67928a8ec1fa</id><uid_owner>user0</uid_owner><share_type>0</share_type><displayname_owner>One</displayname_owner><permissions>19</permissions><stime>1591354676</stime><parent/><expiration/><token/><uid_file_owner>user0</uid_file_owner><displayname_file_owner>One</displayname_file_owner><additional_info_owner/><additional_info_file_owner/><state>0</state><path>/textfile0.txt</path><item_type>file</item_type><mimetype>text/plain</mimetype><storage_id>1284d238-aa92-42ce-bdc4-0b0000009162</storage_id><storage>0</storage><item_source>46e810dc-309a-49f0-ba68-d182fa12b1c5</item_source><file_source>46e810dc-309a-49f0-ba68-d182fa12b1c5</file_source><file_parent/><file_target>/textfile0.txt</file_target><share_with>user2</share_with><share_with_displayname>Two</share_with_displayname><share_with_additional_info/><mail_send/><name/>
  </data>
</ocs>
```
### PROPFIND for reciever for shared resource:
```
curl -u user2:AaBb2Cc3Dd4 -X PROPFIND http://localhost:9140/remote.php/dav/files/user2/textfile0.txt -v
```
  **Response**:
    HTTP/1.1 404 Not Found
```
curl -u user2:AaBb2Cc3Dd4 -X PROPFIND http://localhost:9140/remote.php/dav/files/user2/textfile0.txt -v
```
  **Response**:
    HTTP/1.1 404 Not Found

### get shares for user0:
```
curl -u user0:123456 http://localhost:9140/ocs/v1.php/apps/files_sharing/api/v1/shares -v | xmllint --format -
```
**Response**:
```xml
HTTP/1.1 200 OK
<?xml version="1.0" encoding="UTF-8"?>
<ocs>
  <meta>
    <status>ok</status>
    <statuscode>100</statuscode>
    <message>OK</message>
  </meta>
  <data>
    <element>
      <id>c99b869f-0830-424e-85b3-bd115ced6682</id><share_type>0</share_type><uid_owner>user0</uid_owner><displayname_owner>One</displayname_owner><permissions>19</permissions><stime>1591354468</stime><parent></parent><expiration></expiration><token></token><uid_file_owner>user0</uid_file_owner><displayname_file_owner>One</displayname_file_owner><additional_info_owner></additional_info_owner><additional_info_file_owner></additional_info_file_owner><state>0</state><path>/textfile0.txt</path><item_type>file</item_type><mimetype>text/plain</mimetype><storage_id>1284d238-aa92-42ce-bdc4-0b0000009162</storage_id><storage>0</storage><item_source>46e810dc-309a-49f0-ba68-d182fa12b1c5</item_source><file_source>46e810dc-309a-49f0-ba68-d182fa12b1c5</file_source><file_parent></file_parent><file_target>/textfile0.txt</file_target><share_with>user1</share_with><share_with_displayname>One</share_with_displayname><share_with_additional_info></share_with_additional_info><mail_send></mail_send><name></name>
    </element>
    <element>
      <id>be914aab-9c8c-4285-80b9-67928a8ec1fa</id><share_type>0</share_type><uid_owner>user0</uid_owner><displayname_owner>One</displayname_owner><permissions>19</permissions><stime>1591354676</stime><parent></parent><expiration></expiration><token></token><uid_file_owner>user0</uid_file_owner><displayname_file_owner>One</displayname_file_owner><additional_info_owner></additional_info_owner><additional_info_file_owner></additional_info_file_owner><state>0</state><path>/textfile0.txt</path><item_type>file</item_type><mimetype>text/plain</mimetype><storage_id>1284d238-aa92-42ce-bdc4-0b0000009162</storage_id><storage>0</storage><item_source>46e810dc-309a-49f0-ba68-d182fa12b1c5</item_source><file_source>46e810dc-309a-49f0-ba68-d182fa12b1c5</file_source><file_parent></file_parent><file_target>/textfile0.txt</file_target><share_with>user2</share_with><share_with_displayname>Two</share_with_displayname><share_with_additional_info></share_with_additional_info><mail_send></mail_send><name></name>
    </element>
  </data>
</ocs>
```
Configurations: 
ocis-reva: current master
started as:
```sh
export REVA_STORAGE_HOME_DATA_TEMP_FOLDER='/var/tmp/'
export REVA_STORAGE_LOCAL_ROOT='/var/tmp/reva/root'
export REVA_STORAGE_OWNCLOUD_DATADIR='/var/tmp/reva/data'
export REVA_STORAGE_OC_DATA_TEMP_FOLDER='/var/tmp/'
export REVA_OIDC_ISSUER=https://172.17.0.1:9130
export REVA_USERS_DRIVER='ldap'
export REVA_LDAP_HOSTNAME='localhost'
export REVA_STORAGE_HOME_EXPOSE_DATA_SERVER=1
export REVA_STORAGE_OC_EXPOSE_DATA_SERVER=1
export REVA_STORAGE_OWNCLOUD_REDIS_ADDR=localhost:6379
export REVA_LDAP_PORT=636
export REVA_LDAP_BIND_DN='cn=admin,dc=owncloud,dc=com'
export REVA_LDAP_BIND_PASSWORD='admin'
export REVA_LDAP_BASE_DN='dc=owncloud,dc=com'
export REVA_LOG_PRETTY='true'
export REVA_LOG_COLOR='true'

$HOME/www/ocis-reva/bin/ocis-reva gateway &
$HOME/www/ocis-reva/bin/ocis-reva users &
$HOME/www/ocis-reva/bin/ocis-reva auth-basic &
$HOME/www/ocis-reva/bin/ocis-reva auth-bearer &
$HOME/www/ocis-reva/bin/ocis-reva sharing &
$HOME/www/ocis-reva/bin/ocis-reva storage-home &
$HOME/www/ocis-reva/bin/ocis-reva storage-home-data &
$HOME/www/ocis-reva/bin/ocis-reva storage-oc &
$HOME/www/ocis-reva/bin/ocis-reva storage-oc-data &
$HOME/www/ocis-reva/bin/ocis-reva frontend
```

**Comment by kiranparajuli589** [comment]
After the behavior change, now the bug is in shares responses which shows `created` for the shares that are actually not created, and the status codes for OCS share APIs.

The issue has been created describing the behavior at #250

**Comment by individual-it** [comment]
The fact that `/home` sharing does not work is fine, we don't need it anymore, because the user is jailed in `/home` all the time.
The other thing looks like we still cannot receive shares.

@C0rby do you want to have a new ticket or keep this open?

**Comment by C0rby** [comment]
IMO we can keep this open.

**Comment by PVince81** [comment]
let's check with EOS first. please check using docker-compose

**Comment by individual-it** [comment]
closing in favour of #243
