### ISSUE TITLE
micro/cli update broke users and storage-root service

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis-reva#75]
```
 .\ocis-reva.exe users
{"level":"info","service":"reva","time":"2020-02-04T11:19:34+01:00","message":"Continue without config"}
panic: interface conversion: flag.Value is *flag.stringValue, not *cli.StringSlice

goroutine 1 [running]:
github.com/micro/cli/v2.lookupStringSlice(...)
        C:/Users/jfd/go/pkg/mod/github.com/micro/cli/v2@v2.1.1/flag_string_slice.go:152
github.com/micro/cli/v2.(*Context).StringSlice(0xc000487080, 0x11b383b, 0x7, 0xc0001b8ab0, 0x4, 0x0)
        C:/Users/jfd/go/pkg/mod/github.com/micro/cli/v2@v2.1.1/flag_string_slice.go:144 +0x10b
github.com/owncloud/ocis-reva/pkg/command.Users.func1(0xc000487080, 0x1d, 0x38)
        C:/Users/jfd/test/ocis-reva/pkg/command/users.go:26 +0x54
github.com/micro/cli/v2.(*Command).Run(0xc0001a8360, 0xc000486840, 0x0, 0x0)
        C:/Users/jfd/go/pkg/mod/github.com/micro/cli/v2@v2.1.1/command.go:148 +0x583
github.com/micro/cli/v2.(*App).RunContext(0xc000500300, 0x17ba460, 0xc0000300c0, 0xc000004480, 0x2, 0x2, 0x0, 0x0)
        C:/Users/jfd/go/pkg/mod/github.com/micro/cli/v2@v2.1.1/app.go:302 +0x797
github.com/micro/cli/v2.(*App).Run(...)
        C:/Users/jfd/go/pkg/mod/github.com/micro/cli/v2@v2.1.1/app.go:210
github.com/owncloud/ocis-reva/pkg/command.Execute(0xfa8bc0, 0xc000038118)
        C:/Users/jfd/test/ocis-reva/pkg/command/root.go:102 +0xa19
main.main()
        C:/Users/jfd/test/ocis-reva/cmd/ocis-reva/main.go:10 +0x29
```
and
```
.\ocis-reva.exe storage-root
{"level":"info","service":"reva","time":"2020-02-04T11:10:44+01:00","message":"Continue without config"}
panic: interface conversion: flag.Value is *flag.stringValue, not *cli.StringSlice

goroutine 1 [running]:
github.com/micro/cli/v2.lookupStringSlice(...)
        C:/Users/jfd/go/pkg/mod/github.com/micro/cli/v2@v2.1.1/flag_string_slice.go:152
github.com/micro/cli/v2.(*Context).StringSlice(0xc00003bdc0, 0x11b383b, 0x7, 0xc0001c8090, 0x4, 0x0)
        C:/Users/jfd/go/pkg/mod/github.com/micro/cli/v2@v2.1.1/flag_string_slice.go:144 +0x10b
github.com/owncloud/ocis-reva/pkg/command.StorageRoot.func1(0xc00003bdc0, 0x26, 0x50)
        C:/Users/jfd/test/ocis-reva/pkg/command/storageroot.go:26 +0x54
github.com/micro/cli/v2.(*Command).Run(0xc0000b7c20, 0xc00003b2c0, 0x0, 0x0)
        C:/Users/jfd/go/pkg/mod/github.com/micro/cli/v2@v2.1.1/command.go:148 +0x583
github.com/micro/cli/v2.(*App).RunContext(0xc000074780, 0x17ba460, 0xc0000300b8, 0xc000004480, 0x2, 0x2, 0x0, 0x0)
        C:/Users/jfd/go/pkg/mod/github.com/micro/cli/v2@v2.1.1/app.go:302 +0x797
github.com/micro/cli/v2.(*App).Run(...)
        C:/Users/jfd/go/pkg/mod/github.com/micro/cli/v2@v2.1.1/app.go:210
github.com/owncloud/ocis-reva/pkg/command.Execute(0xfa8bc0, 0xc000038118)
        C:/Users/jfd/test/ocis-reva/pkg/command/root.go:102 +0xa19
main.main()
        C:/Users/jfd/test/ocis-reva/cmd/ocis-reva/main.go:10 +0x29
```

@C0rby may already have an idea what is necessary to fix this.

**Comment by butonic** [comment]
sharing was broken by the namespace change in https://github.com/owncloud/ocis-reva/pull/68
see comment in https://github.com/owncloud/ocis-reva/pull/76#issuecomment-584644700
